### ISSUE TITLE
(Minecraft Fabric Crash) java.lang.AbstractMethodError: Receiver class com.ordana.molten_metals.fluids.MoltenIronFluid$Source does not define or inherit an implementation of the resolved method 'abstract net.minecraft.fluid.Fluid getStill()' of abstract class net.minecraft.fluid.FlowableFluid.

### ISSUE THREAD

**Issue by UnKabaraQuiDev** [AstralOrdana/molten-metals#11]
I'm creating an addon for `create-fabric-1.20.1-0.5.1-h-build.1528+mc1.20.1` and need molten metal, so i checked out `create-molten-metals-1.20.1-0.1.3-fabric`.

These are my dependencies for molten-metals and its dependency, moonlight:
```
// https://www.curseforge.com/minecraft/mc-mods/create-molten-metals/files/5370099
modImplementation "curse.maven:create-molten-metals-1010908:5370099"

// https://www.curseforge.com/minecraft/mc-mods/selene/files/5370700
modImplementation "curse.maven:selene-499980:5370700"
```

However my game crashes on initialization because of:
`java.lang.AbstractMethodError: Receiver class com.ordana.molten_metals.fluids.MoltenIronFluid$Source does not define or inherit an implementation of the resolved method 'abstract net.minecraft.fluid.Fluid getStill()' of abstract class net.minecraft.fluid.FlowableFluid.`

_Crash report_
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 2024-09-26 20:27:33
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'moonlight' at 'net.mehvahdjukaar.moonlight.fabric.MoonlightFabricClient'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.AbstractMethodError: Receiver class com.ordana.molten_metals.fluids.MoltenIronFluid$Source does not define or inherit an implementation of the resolved method 'abstract net.minecraft.fluid.Fluid getStill()' of abstract class net.minecraft.fluid.FlowableFluid.
	at net.minecraft.fluid.FlowableFluid.getStill(FlowableFluid.java:251)
	at net.minecraft.block.FluidBlock.<init>(FluidBlock.java:45)
	at com.ordana.molten_metals.fabric.blocks.MoltenMetalBlock.<init>(MoltenMetalBlock.java:23)
	at com.ordana.molten_metals.fabric.MoltenMetalsPlatformImpl.doMoltenMetal(MoltenMetalsPlatformImpl.java:13)
	at com.ordana.molten_metals.MoltenMetalsPlatform.doMoltenMetal(MoltenMetalsPlatform.java)
	at com.ordana.molten_metals.reg.ModBlocks.lambda$static$2(ModBlocks.java:52)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegistryQueue$EntryWrapper.initialize(RegistryQueue.java:89)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegistryQueue.initializeEntries(RegistryQueue.java:47)
	at net.mehvahdjukaar.moonlight.api.platform.fabric.RegHelperImpl.lateRegisterEntries(RegHelperImpl.java:82)
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabric.commonSetup(MoonlightFabric.java:60)
	at net.mehvahdjukaar.moonlight.fabric.MoonlightFabricClient.onInitializeClient(MoonlightFabricClient.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.8.0-45-generic
	Java Version: 21.0.4, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Eclipse Adoptium
	Memory: 181369776 bytes (172 MiB) / 570425344 bytes (544 MiB) up to 8401190912 bytes (8012 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: GA106 [GeForce RTX 3060 Lite Hash Rate]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 27461.28
	Virtual memory used (MB): 17200.73
	Swap memory total (MB): 11444.00
	Swap memory used (MB): 1.00
	JVM Flags: 0 total; 
	Fabric Mods: 
		create: Create 0.5.1-h-build.1528+mc1.20.1
		create-tinker-construct: Create Tinker & Construct 1.0.0
		dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
		fabric-api: Fabric API 0.92.2+1.20.1
		fabric-api-base: Fabric API Base 0.4.31+1802ada577
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
		fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
		fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
		fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
		fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
		fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
		fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
		fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.13+1802ada577
		fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
		fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
		fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
		fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
		fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
		fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
		fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
		fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
		fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
		fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.5
		flywheel: Flywheel 0.6.11-4
		forgeconfigapiport: Forge Config API Port 8.0.0
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 15.2.0.22
		milk: Milk Lib 1.2.60
		minecraft: Minecraft 1.20.1
		mixinextras: MixinExtras 0.4.1
		molten_metals: Create: Molten Metals 1.20.1-0.1.4
		moonlight: Moonlight 1.20-2.11.30
		porting_lib_accessors: Porting Lib Accessors 2.3.5-beta.33+1.20.1
		porting_lib_attributes: Porting Lib Attributes 2.3.5-beta.33+1.20.1
		porting_lib_base: Porting Lib Base 2.3.5-beta.33+1.20.1
		porting_lib_brewing: Porting Lib Brewing 2.3.5-beta.33+1.20.1
		porting_lib_client_events: Porting Lib Client Events 2.3.5-beta.33+1.20.1
		porting_lib_common: Porting Lib Common 2.3.5-beta.33+1.20.1
		porting_lib_config: Porting Lib Config 2.3.5-beta.33+1.20.1
		porting_lib_core: Porting Lib Core 2.3.5-beta.33+1.20.1
		porting_lib_data: Porting Lib Data 2.1.1090+1.20
		porting_lib_entity: Porting Lib Entity 2.3.5-beta.33+1.20.1
		porting_lib_extensions: Porting Lib Extensions 2.3.5-beta.33+1.20.1
		porting_lib_fluids: Porting Lib Fluids 2.3.5-beta.33+1.20.1
		porting_lib_gui_utils: Porting Lib Gui Utils 2.3.5-beta.33+1.20.1
		porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.5-beta.33+1.20.1
		porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.5-beta.33+1.20.1
		porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
		porting_lib_model_loader: Porting Lib Model Loader 2.3.5-beta.33+1.20.1
		porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		porting_lib_models: Porting Lib Models 2.3.5-beta.33+1.20.1
		porting_lib_networking: Porting Lib Networking 2.3.5-beta.33+1.20.1
		porting_lib_obj_loader: Porting Lib Obj Loader 2.3.5-beta.33+1.20.1
		porting_lib_tags: Porting Lib Tags 3.0
		porting_lib_tool_actions: Porting Lib Tool Actions 2.3.5-beta.33+1.20.1
		porting_lib_transfer: Porting Lib Transfer 2.3.5-beta.33+1.20.1
		porting_lib_utility: Porting Lib Utility 2.3.5-beta.33+1.20.1
		reach-entity-attributes: Reach Entity Attributes 2.4.0
		registrate-fabric: Registrate for Fabric 1.3.69-MC1.20.1
	Flywheel Backend: Uninitialized
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by AstralOrdana** [comment]
this is a modding issue, not a bug report. i cant help with this
